# Generated by Django 4.0.3 on 2022-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionDetails', models.CharField(max_length=32)),
                ('sessionLat', models.CharField(max_length=32)),
                ('sessionLong', models.CharField(max_length=32)),
                ('sessionTime', models.TimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
    ]
